[server]
headless = true


[theme]
base = "light"
primaryColor = "#ff69b4"                # Brighter bubblegum pink
backgroundColor = "#fff0f5"             # Light pink lavender blush
secondaryBackgroundColor = "#ffeaf7"    # Soft cherry blossom pink
textColor = "#444444"                   # Gentle dark gray for readability
font = "sans serif"     