[server]
headless = true

[theme]
base = "light"
primaryColor = "#ffb6c1"         
backgroundColor = "#fef8f8"      
secondaryBackgroundColor = "#ffffff"
textColor = "#222222"            
font = "sans serif"
